name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: "blang/latex"
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Build resume
        run: |
           make short
      - name: Build CV
        run: |
          make long
      - name: Upload resume
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: resume.pdf
      - name: Upload CV
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: cv.pdf
  release:
    runs-on: ubuntu-latest
    needs: build
    environment: prod
    steps:
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "cv.pdf,resume.pdf"
          name: release