name: Build
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    container: "blang/latex"
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Build CV
        run: |
           make short
      - name: Build resume
        run: |
          build long
      - name: Upload resume
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: resume.pdf
      - name: Upload CV
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: cv.pdf
