name: Build
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile resume
        uses: xu-cheng/latex-action@v2
        with:
          root_file: CV.tex
          args: --jobname=resume
      - name: Compile CV
        uses: xu-cheng/latex-action@v2
        with:
          root_file: CV.tex
          args: --jobname=cv '\newcommand*{\LONG}{} \input{CV}'
      - name: Upload resume
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: resume.pdf
      - name: Upload CV
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: cv.pdf
