name: Compile and release CV

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build PDFs
    runs-on: ubuntu-latest
    container: "kjarosh/latex:2024.2"
    steps:
      - name: Install prerequisites
        run: apk add make

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build resume
        run: |
          make short

      - name: Build CV
        run: |
          make long

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: |
            resume.pdf
            cv.pdf

  release:
    name: Release PDFs
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: release
          path: ./artifacts

      - name: Get current date
        id: get_date
        run: echo "RELEASE_DATE=$(date +'%d-%m-%Y')" >> $GITHUB_ENV

      - name: Get current commit hash
        id: get_commit
        run: echo "TAG_NAME=v$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Create tag
        run: git tag ${{ env.TAG_NAME }}

      - name: Push tag
        run: git push origin tag ${{ env.TAG_NAME }}

      - name: Release PDFs
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: CV release from ${{ env.RELEASE_DATE }}
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          files: |
            ./artifacts/resume.pdf
            ./artifacts/cv.pdf
